export {default as AiFeatured} from './ai-featured/AiFeatured'
export {default as BannerGetStarted} from './benner-getstarted/BannerGetStarted'
export {default as BlogFeatured} from './blog-featured/BlogFeatured'
export {default as Features} from './features/Features'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as Hero} from './hero/Hero'
export {default as WhatIs} from './what-is-gpt/WhatIs'